### ISSUE TITLE
Wrong version of downloaded files

### ISSUE THREAD

**Issue by Sagittarius-B** [m417z/winbindex#176] opened 2024-06-12 11:52 UTC
When attempting to download win32kfull.sys for Windows 11 22H2/21H2 version 10.0.22621.3007, the downloaded file is not the right version. After renaming the file, we can see in properties that the version does not match  : 
![image](https://github.com/m417z/winbindex/assets/60006345/dc1dc9d8-ef87-4ae9-a3a3-1a39b5d21050)

win32kfull.sys v10.0.22621.3007, displayed download link : https://msdl.microsoft.com/download/symbols/win32kfull.sys/74747AF53a9000/win32kfull.sys
This ends up downloading win32kfull.sys v10.0.22621.2423

Same for various different versions

**Comment by m417z** [comment] 2024-06-12 11:53
Duplicate of https://github.com/m417z/winbindex/issues/139.

**Closed by m417z** 2024-06-12 11:53 UTC

**Comment by Sagittarius-B** [comment] 2024-06-12 12:01
My mistake
Thanks for the great work!
